export const BUSINESS = {
  name: "V3 Tour & Travels",
  brand: "Airport Live",
  connectedBrand: "Airport Live",
  tagline: "Premium Airport Transfers",
  description: "Premium airport transfers across Ludhiana, Chandigarh, and Delhi NCR. Professional chauffeurs, Toyota Innova Crysta comfort, fixed fares, 24/7 WhatsApp booking.",
  primaryService:
    "Premium airport transfers across Ludhiana, Chandigarh, and Delhi NCR. Professional chauffeurs, Toyota Innova Crysta comfort, fixed fares, 24/7 WhatsApp booking.",
  phone: "9888000510",
  phoneFull: "+919888000510",
  whatsapp: "9888000510",
  email: "book@airportlive.in",
  domain: "airportlive.in",
  websiteDisplay: "airportlive.in",
  website: "https://airportlive.in",
  address: "Ludhiana, Punjab, India",
  experience: "20+",
  fleetCount: "100+",
  openingHours: "Mo-Su 00:00-23:59",
  serviceArea: [
    "Ludhiana",
    "Chandigarh",
    "Delhi NCR",
    "Amritsar",
    "Jalandhar",
    "Patiala",
    "Phagwara",
    "Mohali",
    "Panchkula",
  ],
  coreRoutes: [
    "Ludhiana → Delhi Airport",
    "Chandigarh → Delhi Airport",
    "Delhi Airport → Punjab",
    "Ludhiana → Chandigarh Airport",
    "Amritsar → Delhi Airport",
    "Jalandhar → Delhi Airport",
    "Patiala → Delhi Airport",
  ],
};

export const ROUTES = [
  {
    id: 1,
    from: "Ludhiana",
    to: "Delhi Airport",
    time: "5h 30m",
    desc: "Premium Non-Stop Express",
    popular: true,
  },
  {
    id: 2,
    from: "Chandigarh",
    to: "Delhi Airport",
    time: "4h 00m",
    desc: "Corporate Priority Route",
    popular: true,
  },
  {
    id: 3,
    from: "Delhi Airport",
    to: "Ludhiana",
    time: "5h 30m",
    desc: "Safe Arrival Pickup",
    popular: true,
  },
  {
    id: 4,
    from: "Jalandhar",
    to: "Delhi Airport",
    time: "6h 30m",
    desc: "NRIs Favorite Route",
  },
  {
    id: 5,
    from: "Patiala",
    to: "Delhi Airport",
    time: "4h 30m",
    desc: "Comfortable Airport Link",
  },
  {
    id: 6,
    from: "Amritsar",
    to: "Delhi Airport",
    time: "8h 00m",
    desc: "Long Distance Luxury",
  },
];

export const FLEET = [
  {
    id: "innova-crysta",
    name: "Innova Crysta",
    tagline: "The Corporate Standard",
    seats: "6+1",
    luggage: "4 Bags",
    bestFor: "Family & Corporate",
    comfort: "Premium",
    image:
      "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?q=80&w=2070&auto=format&fit=crop",
    features: ["Captain Seats", "Quiet Cabin", "Ample Luggage", "Rear AC Control"],
  },
  {
    id: "premium-sedan",
    name: "Premium Sedan",
    tagline: "Executive Comfort",
    seats: "4+1",
    luggage: "2 Bags",
    bestFor: "Couples & Business",
    comfort: "High",
    image:
      "https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?q=80&w=2070&auto=format&fit=crop",
    features: ["Leather Interior", "Climate Control", "Smooth Ride", "USB Charging"],
  },
  {
    id: "tempo-traveller",
    name: "Tempo Traveller",
    tagline: "Group Travel Redefined",
    seats: "12-16",
    luggage: "10+ Bags",
    bestFor: "Large Groups & Weddings",
    comfort: "Spacious",
    image:
      "https://images.unsplash.com/photo-1570125909232-eb263c188f7e?q=80&w=2070&auto=format&fit=crop",
    features: ["Push-Back Chairs", "Entertainment System", "Extra Legroom", "Uniformed Driver"],
  },
  {
    id: "maruti-xl6",
    name: "Maruti XL6 / SUV",
    tagline: "Versatile Travel",
    seats: "6",
    luggage: "3 Bags",
    bestFor: "Small Families",
    comfort: "Standard",
    image:
      "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?q=80&w=2070&auto=format&fit=crop",
    features: ["Captain Seats", "Hybrid Efficiency", "Flexible Space"],
  },
];

